services:
  app:
    container_name: ai-agent-cnaps
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    extra_hosts:
      - "model-runner.docker.internal:host-gateway"