# ─── Stage 1 : Build Angular ─────────────────────────────────────────────────
FROM node:18-alpine AS build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci --silent

COPY frontend/ .
RUN npm run build -- --configuration production

# ─── Stage 2 : Nginx ─────────────────────────────────────────────────────────
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist/frontend /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
